language: python
python:
  - 3.6
git:
  depth: false
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -e .
script:
  - travis_wait 60 coverage run --source=pyridge --omit=env test/test_coverage.py
  - coveralls
branches:
  only:
    - master
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
