language: python
python:
  - 3.4
  - 3.5
  - 3.6
git:
  depth: false
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -e .
script:
  - coverage run --source=pyelm --omit=env test/test_data.py
  - coveralls
branches:
  only:
    - travis
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
