language: python
python:
  - 3.6
git:
  depth: false
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -e .
script:
  - travis_wait 30 coverage run --source=pyelm --omit=env test/test_kelm.py
  - travis_wait 30 coverage run --source=pyelm --omit=env test/test_nelm.py
  - travis_wait 60 coverage run --source=pyelm --omit=env test/test_adaboost_nelm.py
  - coveralls
branches:
  only:
    - master
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
