language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - python setup.py install
script:
  - coverage run test/test_data.py
  - coveralls
branches:
  only:
    - travis
notifications:
  email: false
after_sucess:
  - echo "Finished"
