language: python
python:
  - 3.6
  - 3.7-dev
git:
  depth: false
install:
  - pip install coveralls PyYAML pytest-cov
  - python setup.py install
  - wget https://www.dropbox.com/s/jj5zmr4hza3jd8d/data.zip
  - unzip data.zip
script:
  - pytest --cov=pyridge
  - coveralls
branches:
  only:
    - master
    - dev
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
