language: python
python:
  - 3.6
git:
  depth: false
install:
  - pip install coveralls
  - python setup.py install
  - wget https://www.dropbox.com/s/jj5zmr4hza3jd8d/data.zip
  - unzip data.zip
script:
  - travis_wait 60 coverage run --source=pyridge --omit=env test/test_coverage.py
  - coveralls
branches:
  only:
    - master
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
