language: python
python:
  - "3.5"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install
script:
  - python test/test_KELM.py
  - python test/test_NELM.py
  - python test/test_AdaBoostNELM.py
branches:
  only:
    - travis
notifications:
  email: false
