language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python tests/test_all_of_the_units.py
branches:
  only:
    - master
