language: python
# Existing Python versions
python:
  - 3.6
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
git:
  depth: false
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install -e .
script:
  - travis_wait 60 coverage run --source=pyridge --omit=env test/test_coverage.py
  - coveralls
branches:
  only:
    - master
notifications:
  email: false
after_sucess:
  - echo "Travis CI built!"
