language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
script:
  - python test/test_KELM.py
  - python test/test_NELM.py
  - python test/test_AdaBoostNELM.py
branches:
  only:
    - master
